# Generated by Django 2.0.5 on 2018-08-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('episode_id', models.IntegerField(primary_key=True, serialize=False)),
                ('episode_show_id', models.IntegerField()),
                ('episode_identifier', models.CharField(max_length=5, unique=True)),
                ('episode_starttime', models.IntegerField()),
                ('episode_endtime', models.IntegerField()),
                ('episode_playlist_id', models.IntegerField()),
                ('episode_listen_again_recorded', models.IntegerField()),
                ('episode_listen_again_active', models.IntegerField()),
                ('episode_listen_again_src', models.CharField(max_length=50)),
                ('episode_active', models.IntegerField()),
                ('episode_featured', models.IntegerField()),
                ('episode_featured_text', models.TextField(blank=True)),
                ('episode_title', models.CharField(blank=True, max_length=50)),
                ('event_type', models.IntegerField()),
                ('event_live_src', models.IntegerField()),
            ],
            options={
                'db_table': 'schedule_event',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('show_id', models.IntegerField(primary_key=True, serialize=False)),
                ('show_name', models.CharField(max_length=50)),
                ('show_text', models.TextField()),
                ('show_image_id', models.IntegerField()),
                ('show_cropped_image_id', models.IntegerField()),
                ('show_logname', models.CharField(max_length=25, unique=True)),
                ('show_sched_original_app_id', models.IntegerField(unique=True)),
                ('show_on_break', models.IntegerField()),
            ],
            options={
                'db_table': 'shows',
                'managed': True,
            },
        ),
    ]
